# Generated by Django 4.2.7 on 2023-11-21 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_equipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicinal_product', models.CharField(max_length=255, verbose_name='Наименование ЛС')),
                ('RD_for_method', models.CharField(max_length=255, verbose_name='НД на метод')),
                ('RD_for_sample', models.CharField(max_length=255, verbose_name='НД на образец')),
                ('Analyzed_Indicator', models.CharField(max_length=100, verbose_name='Анализируемый показатель')),
                ('Standard', models.CharField(max_length=30, verbose_name='Норма по спецификации в НД')),
                ('Test_procedure', models.CharField(max_length=255, verbose_name='Методика испытаний')),
                ('Reagents_used', models.CharField(max_length=255, verbose_name='Используемые реагенты')),
                ('Equipment_used', models.CharField(max_length=255, verbose_name='Используемое оборудование')),
                ('Measurements', models.ImageField(max_length=255, upload_to='', verbose_name='Измерения')),
                ('Formula', models.CharField(max_length=255, verbose_name='Формула')),
                ('Arguments', models.CharField(max_length=30, verbose_name='Аргументы')),
                ('Calculations', models.CharField(max_length=100, verbose_name='Расчеты')),
                ('Analysis_number', models.CharField(max_length=30, verbose_name='Номер аналлиза')),
                ('Analysis_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время анализа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
